title: "Watalappan Website"
description: "A smooth, liquid-glass website celebrating Sri Lankaâ€™s iconic dessert."
baseurl: "/Watalappan_Website"
url: "https://dadark12.github.io"
markdown: kramdown
permalink: pretty
